# Generated by Django 3.2.3 on 2021-05-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('i', models.IntegerField(primary_key=True, serialize=False)),
                ('frontCard', models.CharField(max_length=20)),
                ('backCard', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Translation',
            },
        ),
    ]
